name: bootstrap_flutter
description: Aplicação de responsividade do bootstrap para facilitar a criação de multiplos tamanhos de telas em seus projetos
version: 1.0.0
repository: https://github.com/gabuldev/bootstrap_flutter
homepage: https://gabul.dev/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  golden_toolkit: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
